# Generated by Django 4.1.1 on 2022-12-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_contact_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Form',
            new_name='Contact_Details',
        ),
    ]
