# Generated by Django 4.1.1 on 2022-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_contact_form_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='message',
            field=models.TextField(),
        ),
    ]
