# Generated by Django 4.1.1 on 2023-01-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('projects', '0011_alter_artist_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Album',
        ),
    ]
